# Site settings
title: Hua Blog
SEOTitle: 张华的博客 | Hua Blog
header-img: img/home-bg.jpg
email: billyzhang2010@gmail.com
description: "关于后端与服务、写作者 | 张华，Web & Mobile Lover，Back-End Engineer | 这里是 @Hua张华 的个人博客，与你一起发现更大的世界。"
keyword: "张华, Hua张华, Hua, 张华的博客, Hua Blog, 博客, 个人网站, 互联网"
url: "http://hustbill.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     audi2012
zhihu_username:     huazhang2015
github_username:    hustbill
#twitter_username:  hustbill
facebook_username:  billyzhang2011



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: hustbill

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: hustbill.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "读书 写字 健身 编程 旅行"
sidebar-avatar: /img/avatar-hua.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`




# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "李苦李-谈谈生活，聊聊技术",
        href: "http://www.likuli.com/"
    },{
        title: "当然我在扯淡",
        href: "https://www.yinwang.org/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]
