# Site settings
title: Hua Zhang
email: hua.zhang@wsu.edu
description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
A Java developer with concurrent and parallel programming expereince in distribute systems.
Reading,  writing, coding and running.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hustbill.github.io" # the base hostname & protocol for your site
twitter_username: billyzhang2010
github_username:  hustbill

# Build settings
markdown: kramdown
